name: Dev - Build & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_sonar:
        description: 'Run SonarQube analysis'
        required: false
        default: false
        type: boolean

env:
  SERVICE_NAME: patient-portal
  AWS_DEFAULT_REGION: us-east-1
  ENVIRONMENT: dev
  ECR_REGISTRY: 560668774271.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: '${{ env.AWS_DEFAULT_REGION }}'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: sonar
        if: ${{ inputs.run_sonar }}
        env:
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
          SONAR_HOST_URL: '${{ vars.SONAR_HOST_URL }}'
        run: |
          mvn clean install sonar:sonar -Dsonar.projectKey=${{ env.SERVICE_NAME }} -Dsonar.projectName=${{ env.SERVICE_NAME }}

      # Backend Build
      - name: Build and push Docker - Backend
        id: build-image-backend
        env:
          IMAGE_TAG: 'build-${{ github.run_number }}'
        run: |
          docker build -t ${{ env.ECR_REGISTRY }}/${{ env.SERVICE_NAME }}/backend-${{ env.ENVIRONMENT }}:$IMAGE_TAG .
          docker push ${{ env.ECR_REGISTRY }}/${{ env.SERVICE_NAME }}/backend-${{ env.ENVIRONMENT }}:$IMAGE_TAG
          echo "image=${{ env.ECR_REGISTRY }}/${{ env.SERVICE_NAME }}/backend-${{ env.ENVIRONMENT }}:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # Frontend Build
      - name: Build and push Docker - Frontend
        id: build-image-frontend
        env:
          IMAGE_TAG: 'build-${{ github.run_number }}'
        run: |
          docker build -f src/frontend/Dockerfile-frontend -t ${{ env.ECR_REGISTRY }}/${{ env.SERVICE_NAME }}/frontend-${{ env.ENVIRONMENT }}:$IMAGE_TAG ./src/frontend
          docker push ${{ env.ECR_REGISTRY }}/${{ env.SERVICE_NAME }}/frontend-${{ env.ENVIRONMENT }}:$IMAGE_TAG
          echo "image=${{ env.ECR_REGISTRY }}/${{ env.SERVICE_NAME }}/frontend-${{ env.ENVIRONMENT }}:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # Update backend image
      - name: Update Task Definition - Backend
        id: task-def-backend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: 'infra/${{ env.SERVICE_NAME }}-${{ env.ENVIRONMENT }}-task-def.json'
          container-name: backend-service
          image: ${{ steps.build-image-backend.outputs.image }}

      # Update frontend image using the rendered backend task definition
      - name: Update Task Definition - Frontend
        id: task-def-frontend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.task-def-backend.outputs.task-definition }}
          container-name: frontend-service
          image: ${{ steps.build-image-frontend.outputs.image }}

      # Deploy
      - name: Deploy ECS Task
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: '${{ steps.task-def-frontend.outputs.task-definition }}'
          service: '${{ env.SERVICE_NAME }}-${{ env.ENVIRONMENT }}-service'
          cluster: 'mc-${{ env.ENVIRONMENT }}-cluster'
          wait-for-service-stability: true